#!/usr/bin/env node

/**
 * GitHub Issues Uploader for StellarVault
 * 
 * This script reads issues from issues.json and creates them on GitHub using GitHub CLI.
 * 
 * Prerequisites:
 * - GitHub CLI (gh) installed and authenticated
 * - Run from project root
 * - GitHub repo: NovaCoreLabs1/StellarVault
 * 
 * Usage:
 * node infra/scripts/upload-issues.js [--dry-run] [--start N] [--limit N]
 * 
 * Examples:
 * node infra/scripts/upload-issues.js                    # Upload all issues
 * node infra/scripts/upload-issues.js --dry-run          # Dry run (show what would be created)
 * node infra/scripts/upload-issues.js --start 50 --limit 10  # Upload 10 issues starting from #50
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const REPO = 'NovaCoreLabs1/StellarVault';
const ISSUES_FILE = path.join(__dirname, 'issues.json');

// Parse command line arguments
const args = process.argv.slice(2);
const isDryRun = args.includes('--dry-run');
const startIndex = Math.max(0, parseInt(args[args.indexOf('--start') + 1] || 0, 10) - 1);
const limit = parseInt(args[args.indexOf('--limit') + 1] || Infinity, 10);

console.log('🚀 StellarVault GitHub Issues Uploader\n');
console.log(`Repository: ${REPO}`);
console.log(`Dry Run: ${isDryRun ? 'YES' : 'NO'}\n`);

// Check prerequisites
function checkPrerequisites() {
  try {
    execSync('gh --version', { stdio: 'pipe' });
  } catch (error) {
    console.error(
      '❌ Error: GitHub CLI (gh) not found. Please install it first:',
    );
    console.error('   https://cli.github.com');
    process.exit(1);
  }

  if (!fs.existsSync(ISSUES_FILE)) {
    console.error(`❌ Error: Issues file not found at ${ISSUES_FILE}`);
    console.error('   Run: node infra/scripts/generate-issues.js');
    process.exit(1);
  }
}

// Load issues
function loadIssues() {
  const content = fs.readFileSync(ISSUES_FILE, 'utf-8');
  return JSON.parse(content);
}

// Create labels if they don't exist
function ensureLabels(labels) {
  const uniqueLabels = [...new Set(labels)];

  uniqueLabels.forEach((label) => {
    try {
      if (!isDryRun) {
        const labelConfig = getLabelConfig(label);
        execSync(`gh label create "${label}" --description "${labelConfig.description}" --color "${labelConfig.color}" || true`, {
          stdio: 'pipe',
          cwd: process.cwd(),
        });
      }
    } catch (error) {
      // Label might already exist, ignore
    }
  });
}

// Get label color configuration
function getLabelConfig(label) {
  const configs = {
    frontend: { description: 'Frontend/UI work', color: '0052CC' },
    backend: { description: 'Backend/API work', color: '5319E7' },
    contracts: { description: 'Smart contracts work', color: '009800' },
    devops: { description: 'DevOps/Infrastructure', color: 'FF6600' },
    testing: { description: 'Testing and QA', color: 'FBCA04' },
    documentation: { description: 'Documentation', color: 'D4C5F9' },
    auth: { description: 'Authentication related', color: '0D47A1' },
    wallet: { description: 'Wallet integration', color: '1B1B1B' },
    payments: { description: 'Payments and transactions', color: '109618' },
    notifications: { description: 'Notifications and messaging', color: 'F08030' },
    deployment: { description: 'Deployment and releases', color: 'FF6D00' },
    'code-quality': { description: 'Code quality improvements', color: '00E5FF' },
    security: { description: 'Security related', color: 'D73A49' },
    performance: { description: 'Performance optimization', color: 'FFC300' },
    bug: { description: 'Bug report', color: 'D73A49' },
    enhancement: { description: 'Feature enhancement', color: '0075CA' },
    'good-first-issue': { description: 'Good for newcomers', color: '7057FF' },
    'help-wanted': { description: 'Help wanted', color: '008672' },
    'type-cleanup': { description: 'Code cleanup', color: 'D4C5F9' },
  };

  return (
    configs[label] || {
      description: label,
      color: 'CCCCCC',
    }
  );
}

// Create a single issue
function createIssue(issue) {
  const title = `${issue.title}`;
  const priority = `Priority: ${issue.priority}`;
  const effort = `Effort: ${issue.effort}`;

  let body = `${issue.description}\n\n`;
  body += `## Details\n`;
  body += `- **Priority**: ${issue.priority}\n`;
  body += `- **Estimated Effort**: ${issue.effort}\n`;
  body += `- **Category**: ${issue.category}\n\n`;

  body += `## Acceptance Criteria\n`;
  issue.acceptance_criteria.forEach((ac) => {
    body += `- [ ] ${ac}\n`;
  });

  body += `\n---\n`;
  body += `*Issue auto-generated by StellarVault issue generator*`;

  const labels = [...issue.labels, issue.priority.toLowerCase(), issue.effort.toLowerCase()];

  if (isDryRun) {
    console.log(`\n📋 [DRY RUN] Would create issue:`);
    console.log(`   Title: ${title}`);
    console.log(`   Labels: ${labels.join(', ')}`);
    console.log(`   Body preview: ${body.substring(0, 100)}...`);
    return true;
  }

  try {
    const labelArgs = labels.map((l) => `--label "${l}"`).join(' ');
    const command = `gh issue create --repo "${REPO}" --title "${title}" --body "${body.replace(/"/g, '\\"').replace(/\n/g, '\\n')}" ${labelArgs}`;

    const output = execSync(command, { encoding: 'utf-8' });
    console.log(`✅ Created issue #${issue.number}: ${title}`);
    console.log(`   URL: ${output.trim()}`);
    return true;
  } catch (error) {
    console.error(`❌ Failed to create issue #${issue.number}: ${title}`);
    console.error(`   Error: ${error.message}`);
    return false;
  }
}

// Main execution
async function main() {
  checkPrerequisites();

  const issues = loadIssues();
  const issuesToProcess = issues.slice(startIndex, startIndex + limit);

  console.log(`📊 Statistics:`);
  console.log(`   Total issues in file: ${issues.length}`);
  console.log(`   Issues to process: ${issuesToProcess.length}`);
  console.log(`   Starting from issue: #${issues[startIndex]?.number || 1}`);

  // Collect all labels
  const allLabels = new Set();
  issuesToProcess.forEach((issue) => {
    issue.labels.forEach((label) => allLabels.add(label));
  });

  console.log(`\n🏷️  Ensuring labels exist...`);
  ensureLabels(Array.from(allLabels));

  console.log(`\n📝 Creating issues...\n`);

  let successCount = 0;
  let failureCount = 0;

  for (const issue of issuesToProcess) {
    const success = createIssue(issue);
    if (success) {
      successCount++;
    } else {
      failureCount++;
    }

    // Rate limiting: GitHub API has limits
    if (!isDryRun && successCount % 5 === 0) {
      console.log('⏳ Rate limiting - waiting 2 seconds...\n');
      await new Promise((resolve) => setTimeout(resolve, 2000));
    }
  }

  // Summary
  console.log(`\n${'='.repeat(50)}`);
  console.log(`📊 Summary:`);
  console.log(`   Created: ${successCount}`);
  console.log(`   Failed: ${failureCount}`);
  console.log(`   Total: ${issuesToProcess.length}`);

  if (isDryRun) {
    console.log(`\n💡 This was a dry run. Issues were not actually created.`);
    console.log(`   Run without --dry-run to create issues.`);
  } else {
    console.log(`\n✨ Issues uploaded successfully!`);
    console.log(`   View them at: https://github.com/${REPO}/issues`);
  }

  process.exit(failureCount > 0 ? 1 : 0);
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
